### PR TITLE
Changed PGP backend from ObjectivePGP to GopenPGP

### PR DESCRIPTION
**Pull request by ZortacDev**
Changes the PGP backend from ObjectivePGP to ProtonMail's GopenPGP (https://gopenpgp.org) as discussed in #205 in order to enable the use of ECC PGP keys. A custom go wrapper is used to just expose and simplify the functionalities needed (see go/src/gopenpgpwrapper.go). As I was not able to include the Go build step in Xcode, I've included the binary produced by gomobile in this commit.

Things remaining to do:
- Include the gomobile build in Xcode
- Report errors from the Go wrapper. As of now the Go code fails silently e.g. in the event of an invalid key, which may result in weird states of the password repo where the app thinks a password has been created but the underlying file is missing/empty.

Because of these possible weird states I wouldn't recommend publishing this version to the App Store until the issues are resolved.

### CODE REVIEW

**Comment by mssun** [comment]
Thank you so much! I can merge this once the gomobile build is ready and release it in the testflight channel.

**Comment by ZortacDev** [comment]
I've created a gopenpgp_build.sh script to automate the build. The only prerequisite is having go installed (can be done with `brew install go`).

**Comment by mssun** [comment]
You can simply add this in the `.travis.yml` file to make CI work. (https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos)
```
addons:
  homebrew:
    packages:
    - go
```

**Comment by mssun** [comment]
Thank you so much! I'll merge it and release in the TestFlight channel.

**Comment by ZortacDev** [comment]
As the ProtonMail guys are doing some major API refactoring, I'll probably do a rewrite with proper error handling once that is completed.

**Comment by savyajha** [comment]
Thank you for this work. It's very good to be able to use an ecc key everywhere now, pass was the one place where I was abstaining.

**Pull request merged**
