### PR TITLE
Move to Swift Package Manager disregarding Cocoapods

### LINKED ISSUE #490: SSH clone fails with "Unsupported URL protocol" error
This only happens in the beta version for 0.12.0 of Pass for iOS. In 0.11.0 cloning the same repository works fine. It seems like the update of ObjectiveGit from "0.15" to "master" in 6581f159 causes the issue. 

The error "Unsupported URL protocol" could mean that `libssh2` is not available or not properly configured as mentioned [here](https://github.com/libgit2/objective-git/issues/640#issuecomment-357687416).

### PR DESCRIPTION
**Pull request by SimplyDanny**
Now that SPM is integrated into Xcode and works for iOS project, many project seem to move to it. I would like to give it a try, too. The project setup becomes a bit easier and the project structure looks clearer, I think.

* Build as many dependencies as possible with SPM.
* Xcworkspace is no longer needed.
* Collecting coverage information does unfortunately cause linking errors in Base32. So it is disabled for now.
* Build XCFrameworks with Carthage.

The build of the ObjectiveGit fork fails with a linker error. This has nothing to do with the switch to SPM, though. I'm not sure why the fork is needed at all. There was some activity in the upstream repository recently, so maybe we can move back to it? Turns out that this would also fix #490. Otherwise I can replace `"libgit2/objective-git"` by `"mssun/objective-git"` again.

### CODE REVIEW

**Comment by mssun** [comment]
Thanks Danny. Basically, the `mssun/objective-git` fork has these updates (and with some building fixes):
- Update libgit2 to v0.28.3
- Update libssh2 to 1.9.0
- Use openssl-apple and openssl 1.1.1

If I remember correctly, I updated these dependency to support ECDSA key for SSH cloning. 

Therefore, we need either upstream the changes of my dependency updates or merge upstream changes to my fork.

**Comment by SimplyDanny** [comment]
I managed to build the fork successfully as a normal framework (no XCFramework). This is anyway not yet required and can also be done separately afterwards when the other changes are okay.

For ObjectivePGP I also used the upstream repository, because it contains the `Package.swift`. As far as I see, we only use `mssun/ObjectivePGP`, because of one more fix (which did not convince the maintainer). So we can either dismiss the fork and move back to upstream or [update the fork](https://github.com/mssun/ObjectivePGP/pull/1). @mssun, please decide. 🙂

**Comment by mssun** [comment]
I read through related threads around this fix:
- https://github.com/mssun/ObjectivePGP/commit/a1861cd020c56f9df402a43197b43ab6c582b099
- https://github.com/krzyzanowskim/ObjectivePGP/pull/160

We can switch back to upstream ObjectivePGP. I'll update here if anything wrong.

**Comment by mssun** [comment]
I don't know why the App Store Connect report this error for the build:

```
[17:17:29]: [Transporter Error Output]: ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.krzyzanowskim.ObjectivePGP' under the iOS application 'Pass Beta.app'."

[17:17:29]: [Transporter Error Output]: ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'OneTimePassword' under the iOS application 'Pass Beta.app'."
...
```

https://github.com/mssun/passforios/runs/3464311456#step:10:495

**Comment by SimplyDanny** [comment]
This seems to be a bug in Xcode. We may try with #501.

**Comment by sanderdekoning** [comment]
@SimplyDanny can you please elaborate on your setup for me? I'm running into the same issue you had (https://github.com/mssun/passforios/issues/490) and it's getting me a bit stumped - it seems that every time when I get a new iPhone/there is an iOS upgrade I try to build the project again and it just doesn't work. I'm building with Xcode 13.1 for iOS 15

**Comment by SimplyDanny** [comment]
What exactly are you interested in, @sanderdekoning? On Intel the steps mentioned in the README should work:

* Install Homebrew dependencies.
* Run `./scripts/wcarthage bootstrap --platform iOS`. Note that the `--use-xcframeworks` does currently not yet work.
* Run `./scripts/gopenpgp_build.sh`.
* Open the project and build.

Where are you getting issues? The build on Apple Silicon works somehow but you cannot run the app in the simulator. This is due to the missing arm64 macOS target in Objective-Git. I already had success in building it manually and are currently working on bringing it back to upstream or at least the fork `mssun/objective-git`.

**Comment by sanderdekoning** [comment]
Thanks for contacting @SimplyDanny - see my comment https://github.com/mssun/passforios/issues/519#issuecomment-986093762 on how I managed to get the build working. Indeed I used `--use-xcframeworks` and it seemed to work in my case. Then when the built succeeded I would always get the `unsupported url protocol` error. It appears that I could resolve that by adding `export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/libssh2/lib/pkgconfig/"`  and rebuilding (including golang script) https://github.com/mssun/passforios/blob/afe0397dcf1ca5522d27e5744fcfa79598f32123/.github/workflows/deploying.yml#L44

**Pull request merged**
