### PR TITLE
Get username from filepath.

### PR DESCRIPTION
**Pull request by merisbahti**

### CODE REVIEW

**Comment by yishilin14** [comment]
Thank you for your PR.

I don't this it is a good idea to extract usernames like this. This is not a common way for people to name their entries. For example, people could have entries like "fun/xxx", "video/xxx", "work/xxx".

**Comment by merisbahti** [comment]
It gets the filename from the last entry in the file-path, so if the path is `"fun/facebook.com/myname"`, the username would be resolved to `"myname"`

**Comment by yishilin14** [comment]
For me, I use either "xxx.com" or "path/xxx.com" as the entry name.

**Comment by merisbahti** [comment]
I still believe getting the filename from the path is better than just sending an empty string, since it's annoying that the password manager clears the username/email field when getting the password.

**Comment by yishilin14** [comment]
I read issue #239 and [the documentation of browserpass/browserpass-extension](https://github.com/browserpass/browserpass-extension#organizing-password-store). Now I know putting username in the filepath is a convention.

In this PR, `pass.xcodeproj/project.pbxproj` gets modified (could be related to #247). Could you please commit the original `pass.xcodeproj/project.pbxproj`? I will squash and merge once it is done.

**Comment by merisbahti** [comment]
Done now!

Awesome, thanks :)

**Pull request merged**
