### PR TITLE
Localization of the App (#208)

### PR DESCRIPTION
**Pull request by SimplyDanny**
First of all, I'm really astonished at how many strings are part of such a relatively small application. 😅

Please take a look at the changes/additions. I hope I caught every string in the code. If it turns out this is everything necessary the following files are the ones which have to be translated:
* `Localizable.strings`
* `Localizable.stringsdict`
* `Main.strings`
* `InfoPlist.strings` in `pass`
* `InfoPlist.strings` in `passExtension`

### CODE REVIEW

**Comment by SimplyDanny** [comment]
In the view about importing ASCII-Armor keys is this text explaining the `-a` option of the `gpg` tool. Unfortunately, I'm currently not able to export this text into the translation file for the storyboard. Even removing the different fonts used did not work. Maybe someone can help.

**Comment by mssun** [comment]
@SimplyDanny This is really an amazing PR!!! Let me take a look.

**Comment by yishilin14** [comment]
This is AWESOME!!!!!!!!!!!!!!!!!!!

**Comment by SimplyDanny** [comment]
Thank you both!

**Pull request merged**
