### PR TITLE
Only show section index when "enough" entries are available.

### PR DESCRIPTION
**Pull request by jeroenleenarts**

### CODE REVIEW

**Comment by jeroenleenarts** [comment]
Fixes #197

**Comment by mssun** [comment]
Thanks @jeroenleenarts for you PR. I think the threshold (i.e., `sections.count < 12`) is so simple that it is not proper in some cases. For example, in the "no folder" case, if there are only two sections but each section has many password entries. The section index will not be shown. (means hard to navigate section)

I think the solution of #197 can be explained like this:

If 1. the numbers of items (no matter they are passwords or folders) is small and 2. when "show folders" is on.
Then 1. do not show items in sections, 2. do not show section index titles.

What do you think?

**Comment by jeroenleenarts** [comment]
Need to look at all code involved to understand the impact. But I do see that my suggested change is too simple.

**Comment by jeroenleenarts** [comment]
@mssun I added a few more lines and I think this should do it. Treshold is 8 items on a screen.

Also I am having some difficulty building the project. Is there a reason you are using a mix of Carthage and CocoaPods? It would be better to use only one of them. I am having a launch error due to the app not finding the `ObjectiveGPG.framework`.

**Comment by mssun** [comment]
Thanks. Yes, I definitely want to unify the package management environment. The reason I'm mixing carthage and pod is because I cannot figure out how to use `ObjectivePGP` with Carthage.

Did you forget to run `pod install` and start with `pass.xcworkspace`?

**Comment by jeroenleenarts** [comment]
Dunno what changed, but was able to create a build.

**Comment by mssun** [comment]
The commit (b9edcea21499881ad6de11671e940b6e8f02f437) fixes this issue. Basically, the behavior is similar with that in Apple's Contact app.

**Pull request closed without merging**
