### PR TITLE
Add support for Yubikey command chaining

### PR DESCRIPTION
**Pull request by ak1394**
I'd like to propose a PR that adds support for command chaining for Yubikeys, which should resolve some issues reported in #42 in particular "Failed to execute decipher" when using large keys.

These changes, however will force dropping support for iOS 12.x and moving to 13.0 as a minimum supported version, due to use of async/await, etc.

### CODE REVIEW

**Comment by ak1394** [comment]
Oh, I see something has kicked off the tests. Testing step fails 'cause the project files, still target platforms older than IOS 13. I suppose I should update the project file and see if it improves things. I wanted to get some feedback first, but I guess there is no harm in doing that.

**Comment by mssun** [comment]
Thanks for the contribution. I'm consider to merge this change in the next release since this will force dropping support for iOS 12.x. What do you think?

**Comment by ak1394** [comment]
I'll be happy if you merge it. I hope bumping up required OS to 13 is not such a big deal now, and given that there is a lot of async stuff in it, I found it difficult to do it with callbacks.

**Comment by mssun** [comment]
merged: https://github.com/mssun/passforios/commit/f6b2316324bf2efb0447b7a0808b5ce0e745db5b

**Pull request closed without merging**
