### PR TITLE
Separate parser and helpers from Password class for better testability

### PR DESCRIPTION
**Pull request by SimplyDanny**
To increase test coverage (at least for the password file parser) I separated the parser stuff from the `Password` class and introduced some helper classes/extensions.

### CODE REVIEW

**Comment by mssun** [comment]
Great! @SimplyDanny This is what I plan to do today actually. Thank you so much. I'm reviewing your change right now.

**Comment by mssun** [comment]
Nice wok! Merged.

**Comment by SimplyDanny** [comment]
Cool! Hope I did not ruin your plans. 😊

**Comment by mssun** [comment]
Not at all. Go ahead and do it!

**Pull request merged**
