### PR TITLE
resolves #456; better instructions for en

### LINKED ISSUE #456: Cannot view any stored pass item after setup
## Tested environments

- the beta version `pass for iOS 0.12.0 (8)` from testflight on ` iOS 14.4` (has this issue)
- the stable version `pass for iOS 0.11.0 (11)` from App Store on ` iOS 14.4` (has this issue)
- `iOS 11.4 running Pass for iOS 0.9.0 (21)` (works without this issue)

## Steps to reproduce:
1. Set up a remote `https` git repo at gitlab via username and password (id_rsa 4096 key and id_ed25519 keys don't seem to be supported... but that is irrelevant to this). 
2. Also exported the gpg keys via local server URL (using `ruby -run -e httpd . -p 8080` and then `http://<local ip>:8080/a.asc` etc.). The import seemed fine, except it warned me not to use http but use https instead. 
3. Then I clicked on one pass item in the Passwords menu.  It asked for the PGP secret key Passphrase. 
4. I filled in the password correctly (I tried 20+ times, even via a bluetooth keyboard); the same password unlocks my gpg on my computer fine). 

## Result
However, once I finish inserting my password and click OK, I get:
```
Cannot show password
gopengp: unable to add locked key to a keyring
```

## Expected results:
The item opens, and shows the item view, where I could copy or show the password.

## Things I have tried to fix/rule out:
- Guessing it may have been talking about iOS keychain, I checked my keychain. It is synced fine with iCloud, and works fine.
- Tried several times after deleting the GPG key and several ways to export the gpg key (via key id, or the email etc.). 
- Also tried importing via iTunes (dropped the keys into the Pass Beta app then clicked iTunes import which showed a prompt saying "success"). 
- Tried deleting the app (along with its data) and completely setting up afresh.

None of those worked. Not sure what went wrong here. 

Let me know what more info I can provide to help debug or resolve this issue with better documentation.

Not sure if it is relevant, but I was using an old `iOS 11.4` running `Pass for iOS 0.9.0 (21)` before which worked (and still works) fine; I just migrated (via backing up to iTunes, ehm, it is called Music now and works directly from within Finder) from that to iOS 14.4.

### PR DESCRIPTION
**Pull request by hyiltiz**
A more detailed instruction (in English only) that resolves #456. Feel free to adjust the language or the instructions to make it more concise and clear.

### CODE REVIEW

**Comment by SimplyDanny** [comment]
Please be not surprised about the revert commit. I accidentally hit the "revert" button. 🤦‍♂️ There is surely nothing to revert.

**Comment by mssun** [comment]
🤦‍♂️ not sure if you can help with the instruction in German.

**Comment by SimplyDanny** [comment]
Sure, I will update the German translation. 👍

**Comment by hyiltiz** [comment]
Awesome, with German instruction updated, it should be good to go. Feel free to polish up the instructions as you like; I have been told I explain things a bit too much.

**Comment by hyiltiz** [comment]
I think this should also close #479 from what I can understand about the description, but haven't tested it with a from-scratch setup for #479 yet.

**Pull request merged**
